type IconName =
  | "3d_rotation"
  | "ac_unit"
  | "access_alarm"
  | "access_alarms"
  | "access_time"
  | "accessibility"
  | "accessible"
  | "account_balance"
  | "account_balance_wallet"
  | "account_box"
  | "account_circle"
  | "adb"
  | "add"
  | "add_a_photo"
  | "add_alarm"
  | "add_alert"
  | "add_box"
  | "add_circle"
  | "add_circle_outline"
  | "add_location"
  | "add_shopping_cart"
  | "add_to_photos"
  | "add_to_queue"
  | "adjust"
  | "airline_seat_flat"
  | "airline_seat_flat_angled"
  | "airline_seat_individual_suite"
  | "airline_seat_legroom_extra"
  | "airline_seat_legroom_normal"
  | "airline_seat_legroom_reduced"
  | "airline_seat_recline_extra"
  | "airline_seat_recline_normal"
  | "airplanemode_active"
  | "airplanemode_inactive"
  | "airplay"
  | "airport_shuttle"
  | "alarm"
  | "alarm_add"
  | "alarm_off"
  | "alarm_on"
  | "album"
  | "all_inclusive"
  | "all_out"
  | "android"
  | "announcement"
  | "apps"
  | "archive"
  | "arrow_back"
  | "arrow_downward"
  | "arrow_drop_down"
  | "arrow_drop_down_circle"
  | "arrow_drop_up"
  | "arrow_forward"
  | "arrow_upward"
  | "art_track"
  | "aspect_ratio"
  | "assessment"
  | "assignment"
  | "assignment_ind"
  | "assignment_late"
  | "assignment_return"
  | "assignment_returned"
  | "assignment_turned_in"
  | "assistant"
  | "assistant_photo"
  | "attach_file"
  | "attach_money"
  | "attachment"
  | "audiotrack"
  | "autorenew"
  | "av_timer"
  | "backspace"
  | "backup"
  | "battery_alert"
  | "battery_charging_full"
  | "battery_full"
  | "battery_std"
  | "battery_unknown"
  | "beach_access"
  | "beenhere"
  | "block"
  | "bluetooth"
  | "bluetooth_audio"
  | "bluetooth_connected"
  | "bluetooth_disabled"
  | "bluetooth_searching"
  | "blur_circular"
  | "blur_linear"
  | "blur_off"
  | "blur_on"
  | "book"
  | "bookmark"
  | "bookmark_border"
  | "border_all"
  | "border_bottom"
  | "border_clear"
  | "border_color"
  | "border_horizontal"
  | "border_inner"
  | "border_left"
  | "border_outer"
  | "border_right"
  | "border_style"
  | "border_top"
  | "border_vertical"
  | "branding_watermark"
  | "brightness_1"
  | "brightness_2"
  | "brightness_3"
  | "brightness_4"
  | "brightness_5"
  | "brightness_6"
  | "brightness_7"
  | "brightness_auto"
  | "brightness_high"
  | "brightness_low"
  | "brightness_medium"
  | "broken_image"
  | "brush"
  | "bubble_chart"
  | "bug_report"
  | "build"
  | "burst_mode"
  | "business"
  | "business_center"
  | "cached"
  | "cake"
  | "call"
  | "call_end"
  | "call_made"
  | "call_merge"
  | "call_missed"
  | "call_missed_outgoing"
  | "call_received"
  | "call_split"
  | "call_to_action"
  | "camera"
  | "camera_alt"
  | "camera_enhance"
  | "camera_front"
  | "camera_rear"
  | "camera_roll"
  | "cancel"
  | "card_giftcard"
  | "card_membership"
  | "card_travel"
  | "casino"
  | "cast"
  | "cast_connected"
  | "center_focus_strong"
  | "center_focus_weak"
  | "change_history"
  | "chat"
  | "chat_bubble"
  | "chat_bubble_outline"
  | "check"
  | "check_box"
  | "check_box_outline_blank"
  | "check_circle"
  | "chevron_left"
  | "chevron_right"
  | "child_care"
  | "child_friendly"
  | "chrome_reader_mode"
  | "class"
  | "clear"
  | "clear_all"
  | "close"
  | "closed_caption"
  | "cloud"
  | "cloud_circle"
  | "cloud_done"
  | "cloud_download"
  | "cloud_off"
  | "cloud_queue"
  | "cloud_upload"
  | "code"
  | "collections"
  | "collections_bookmark"
  | "color_lens"
  | "colorize"
  | "comment"
  | "compare"
  | "compare_arrows"
  | "computer"
  | "confirmation_number"
  | "contact_mail"
  | "contact_phone"
  | "contacts"
  | "content_copy"
  | "content_cut"
  | "content_paste"
  | "control_point"
  | "control_point_duplicate"
  | "copyright"
  | "create"
  | "create_new_folder"
  | "credit_card"
  | "crop"
  | "crop_16_9"
  | "crop_3_2"
  | "crop_5_4"
  | "crop_7_5"
  | "crop_din"
  | "crop_free"
  | "crop_landscape"
  | "crop_original"
  | "crop_portrait"
  | "crop_rotate"
  | "crop_square"
  | "dashboard"
  | "data_usage"
  | "date_range"
  | "dehaze"
  | "delete"
  | "delete_forever"
  | "delete_sweep"
  | "description"
  | "desktop_mac"
  | "desktop_windows"
  | "details"
  | "developer_board"
  | "developer_mode"
  | "device_hub"
  | "devices"
  | "devices_other"
  | "dialer_sip"
  | "dialpad"
  | "directions"
  | "directions_bike"
  | "directions_boat"
  | "directions_bus"
  | "directions_car"
  | "directions_railway"
  | "directions_run"
  | "directions_subway"
  | "directions_transit"
  | "directions_walk"
  | "disc_full"
  | "dns"
  | "do_not_disturb"
  | "do_not_disturb_alt"
  | "do_not_disturb_off"
  | "do_not_disturb_on"
  | "dock"
  | "domain"
  | "done"
  | "done_all"
  | "donut_large"
  | "donut_small"
  | "drafts"
  | "drag_handle"
  | "drive_eta"
  | "dvr"
  | "edit"
  | "edit_location"
  | "eject"
  | "email"
  | "enhanced_encryption"
  | "equalizer"
  | "error"
  | "error_outline"
  | "euro_symbol"
  | "ev_station"
  | "event"
  | "event_available"
  | "event_busy"
  | "event_note"
  | "event_seat"
  | "exit_to_app"
  | "expand_less"
  | "expand_more"
  | "explicit"
  | "explore"
  | "exposure"
  | "exposure_neg_1"
  | "exposure_neg_2"
  | "exposure_plus_1"
  | "exposure_plus_2"
  | "exposure_zero"
  | "extension"
  | "face"
  | "fast_forward"
  | "fast_rewind"
  | "favorite"
  | "favorite_border"
  | "featured_play_list"
  | "featured_video"
  | "feedback"
  | "fiber_dvr"
  | "fiber_manual_record"
  | "fiber_new"
  | "fiber_pin"
  | "fiber_smart_record"
  | "file_download"
  | "file_upload"
  | "filter"
  | "filter_1"
  | "filter_2"
  | "filter_3"
  | "filter_4"
  | "filter_5"
  | "filter_6"
  | "filter_7"
  | "filter_8"
  | "filter_9"
  | "filter_9_plus"
  | "filter_b_and_w"
  | "filter_center_focus"
  | "filter_drama"
  | "filter_frames"
  | "filter_hdr"
  | "filter_list"
  | "filter_none"
  | "filter_tilt_shift"
  | "filter_vintage"
  | "find_in_page"
  | "find_replace"
  | "fingerprint"
  | "first_page"
  | "fitness_center"
  | "flag"
  | "flare"
  | "flash_auto"
  | "flash_off"
  | "flash_on"
  | "flight"
  | "flight_land"
  | "flight_takeoff"
  | "flip"
  | "flip_to_back"
  | "flip_to_front"
  | "folder"
  | "folder_open"
  | "folder_shared"
  | "folder_special"
  | "font_download"
  | "format_align_center"
  | "format_align_justify"
  | "format_align_left"
  | "format_align_right"
  | "format_bold"
  | "format_clear"
  | "format_color_fill"
  | "format_color_reset"
  | "format_color_text"
  | "format_indent_decrease"
  | "format_indent_increase"
  | "format_italic"
  | "format_line_spacing"
  | "format_list_bulleted"
  | "format_list_numbered"
  | "format_paint"
  | "format_quote"
  | "format_shapes"
  | "format_size"
  | "format_strikethrough"
  | "format_textdirection_l_to_r"
  | "format_textdirection_r_to_l"
  | "format_underlined"
  | "forum"
  | "forward"
  | "forward_10"
  | "forward_30"
  | "forward_5"
  | "free_breakfast"
  | "fullscreen"
  | "fullscreen_exit"
  | "functions"
  | "g_translate"
  | "gamepad"
  | "games"
  | "gavel"
  | "gesture"
  | "get_app"
  | "gif"
  | "golf_course"
  | "gps_fixed"
  | "gps_not_fixed"
  | "gps_off"
  | "grade"
  | "gradient"
  | "grain"
  | "graphic_eq"
  | "grid_off"
  | "grid_on"
  | "group"
  | "group_add"
  | "group_work"
  | "hd"
  | "hdr_off"
  | "hdr_on"
  | "hdr_strong"
  | "hdr_weak"
  | "headset"
  | "headset_mic"
  | "healing"
  | "hearing"
  | "help"
  | "help_outline"
  | "high_quality"
  | "highlight"
  | "highlight_off"
  | "history"
  | "home"
  | "hot_tub"
  | "hotel"
  | "hourglass_empty"
  | "hourglass_full"
  | "http"
  | "https"
  | "image"
  | "image_aspect_ratio"
  | "import_contacts"
  | "import_export"
  | "important_devices"
  | "inbox"
  | "indeterminate_check_box"
  | "info"
  | "info_outline"
  | "input"
  | "insert_chart"
  | "insert_comment"
  | "insert_drive_file"
  | "insert_emoticon"
  | "insert_invitation"
  | "insert_link"
  | "insert_photo"
  | "invert_colors"
  | "invert_colors_off"
  | "iso"
  | "keyboard"
  | "keyboard_arrow_down"
  | "keyboard_arrow_left"
  | "keyboard_arrow_right"
  | "keyboard_arrow_up"
  | "keyboard_backspace"
  | "keyboard_capslock"
  | "keyboard_hide"
  | "keyboard_return"
  | "keyboard_tab"
  | "keyboard_voice"
  | "kitchen"
  | "label"
  | "label_outline"
  | "landscape"
  | "language"
  | "laptop"
  | "laptop_chromebook"
  | "laptop_mac"
  | "laptop_windows"
  | "last_page"
  | "launch"
  | "layers"
  | "layers_clear"
  | "leak_add"
  | "leak_remove"
  | "lens"
  | "library_add"
  | "library_books"
  | "library_music"
  | "lightbulb_outline"
  | "line_style"
  | "line_weight"
  | "linear_scale"
  | "link"
  | "linked_camera"
  | "list"
  | "live_help"
  | "live_tv"
  | "local_activity"
  | "local_airport"
  | "local_atm"
  | "local_bar"
  | "local_cafe"
  | "local_car_wash"
  | "local_convenience_store"
  | "local_dining"
  | "local_drink"
  | "local_florist"
  | "local_gas_station"
  | "local_grocery_store"
  | "local_hospital"
  | "local_hotel"
  | "local_laundry_service"
  | "local_library"
  | "local_mall"
  | "local_movies"
  | "local_offer"
  | "local_parking"
  | "local_pharmacy"
  | "local_phone"
  | "local_pizza"
  | "local_play"
  | "local_post_office"
  | "local_printshop"
  | "local_see"
  | "local_shipping"
  | "local_taxi"
  | "location_city"
  | "location_disabled"
  | "location_off"
  | "location_on"
  | "location_searching"
  | "lock"
  | "lock_open"
  | "lock_outline"
  | "looks"
  | "looks_3"
  | "looks_4"
  | "looks_5"
  | "looks_6"
  | "looks_one"
  | "looks_two"
  | "loop"
  | "loupe"
  | "low_priority"
  | "loyalty"
  | "mail"
  | "mail_outline"
  | "map"
  | "markunread"
  | "markunread_mailbox"
  | "memory"
  | "menu"
  | "merge_type"
  | "message"
  | "mic"
  | "mic_none"
  | "mic_off"
  | "mms"
  | "mode_comment"
  | "mode_edit"
  | "monetization_on"
  | "money_off"
  | "monochrome_photos"
  | "mood"
  | "mood_bad"
  | "more"
  | "more_horiz"
  | "more_vert"
  | "motorcycle"
  | "mouse"
  | "move_to_inbox"
  | "movie"
  | "movie_creation"
  | "movie_filter"
  | "multiline_chart"
  | "music_note"
  | "music_video"
  | "my_location"
  | "nature"
  | "nature_people"
  | "navigate_before"
  | "navigate_next"
  | "navigation"
  | "near_me"
  | "network_cell"
  | "network_check"
  | "network_locked"
  | "network_wifi"
  | "new_releases"
  | "next_week"
  | "nfc"
  | "no_encryption"
  | "no_sim"
  | "not_interested"
  | "note"
  | "note_add"
  | "notifications"
  | "notifications_active"
  | "notifications_none"
  | "notifications_off"
  | "notifications_paused"
  | "offline_pin"
  | "ondemand_video"
  | "opacity"
  | "open_in_browser"
  | "open_in_new"
  | "open_with"
  | "pages"
  | "pageview"
  | "palette"
  | "pan_tool"
  | "panorama"
  | "panorama_fish_eye"
  | "panorama_horizontal"
  | "panorama_vertical"
  | "panorama_wide_angle"
  | "party_mode"
  | "pause"
  | "pause_circle_filled"
  | "pause_circle_outline"
  | "payment"
  | "people"
  | "people_outline"
  | "perm_camera_mic"
  | "perm_contact_calendar"
  | "perm_data_setting"
  | "perm_device_information"
  | "perm_identity"
  | "perm_media"
  | "perm_phone_msg"
  | "perm_scan_wifi"
  | "person"
  | "person_add"
  | "person_outline"
  | "person_pin"
  | "person_pin_circle"
  | "personal_video"
  | "pets"
  | "phone"
  | "phone_android"
  | "phone_bluetooth_speaker"
  | "phone_forwarded"
  | "phone_in_talk"
  | "phone_iphone"
  | "phone_locked"
  | "phone_missed"
  | "phone_paused"
  | "phonelink"
  | "phonelink_erase"
  | "phonelink_lock"
  | "phonelink_off"
  | "phonelink_ring"
  | "phonelink_setup"
  | "photo"
  | "photo_album"
  | "photo_camera"
  | "photo_filter"
  | "photo_library"
  | "photo_size_select_actual"
  | "photo_size_select_large"
  | "photo_size_select_small"
  | "picture_as_pdf"
  | "picture_in_picture"
  | "picture_in_picture_alt"
  | "pie_chart"
  | "pie_chart_outlined"
  | "pin_drop"
  | "place"
  | "play_arrow"
  | "play_circle_filled"
  | "play_circle_outline"
  | "play_for_work"
  | "playlist_add"
  | "playlist_add_check"
  | "playlist_play"
  | "plus_one"
  | "poll"
  | "polymer"
  | "pool"
  | "portable_wifi_off"
  | "portrait"
  | "power"
  | "power_input"
  | "power_settings_new"
  | "pregnant_woman"
  | "present_to_all"
  | "print"
  | "priority_high"
  | "public"
  | "publish"
  | "query_builder"
  | "question_answer"
  | "queue"
  | "queue_music"
  | "queue_play_next"
  | "radio"
  | "radio_button_checked"
  | "radio_button_unchecked"
  | "rate_review"
  | "receipt"
  | "recent_actors"
  | "record_voice_over"
  | "redeem"
  | "redo"
  | "refresh"
  | "remove"
  | "remove_circle"
  | "remove_circle_outline"
  | "remove_from_queue"
  | "remove_red_eye"
  | "remove_shopping_cart"
  | "reorder"
  | "repeat"
  | "repeat_one"
  | "replay"
  | "replay_10"
  | "replay_30"
  | "replay_5"
  | "reply"
  | "reply_all"
  | "report"
  | "report_problem"
  | "restaurant"
  | "restaurant_menu"
  | "restore"
  | "restore_page"
  | "ring_volume"
  | "room"
  | "room_service"
  | "rotate_90_degrees_ccw"
  | "rotate_left"
  | "rotate_right"
  | "rounded_corner"
  | "router"
  | "rowing"
  | "rss_feed"
  | "rv_hookup"
  | "satellite"
  | "save"
  | "scanner"
  | "schedule"
  | "school"
  | "screen_lock_landscape"
  | "screen_lock_portrait"
  | "screen_lock_rotation"
  | "screen_rotation"
  | "screen_share"
  | "sd_card"
  | "sd_storage"
  | "search"
  | "security"
  | "select_all"
  | "send"
  | "sentiment_dissatisfied"
  | "sentiment_neutral"
  | "sentiment_satisfied"
  | "sentiment_very_dissatisfied"
  | "sentiment_very_satisfied"
  | "settings"
  | "settings_applications"
  | "settings_backup_restore"
  | "settings_bluetooth"
  | "settings_brightness"
  | "settings_cell"
  | "settings_ethernet"
  | "settings_input_antenna"
  | "settings_input_component"
  | "settings_input_composite"
  | "settings_input_hdmi"
  | "settings_input_svideo"
  | "settings_overscan"
  | "settings_phone"
  | "settings_power"
  | "settings_remote"
  | "settings_system_daydream"
  | "settings_voice"
  | "share"
  | "shop"
  | "shop_two"
  | "shopping_basket"
  | "shopping_cart"
  | "short_text"
  | "show_chart"
  | "shuffle"
  | "signal_cellular_4_bar"
  | "signal_cellular_connected_no_internet_4_bar"
  | "signal_cellular_no_sim"
  | "signal_cellular_null"
  | "signal_cellular_off"
  | "signal_wifi_4_bar"
  | "signal_wifi_4_bar_lock"
  | "signal_wifi_off"
  | "sim_card"
  | "sim_card_alert"
  | "skip_next"
  | "skip_previous"
  | "slideshow"
  | "slow_motion_video"
  | "smartphone"
  | "smoke_free"
  | "smoking_rooms"
  | "sms"
  | "sms_failed"
  | "snooze"
  | "sort"
  | "sort_by_alpha"
  | "spa"
  | "space_bar"
  | "speaker"
  | "speaker_group"
  | "speaker_notes"
  | "speaker_notes_off"
  | "speaker_phone"
  | "spellcheck"
  | "star"
  | "star_border"
  | "star_half"
  | "stars"
  | "stay_current_landscape"
  | "stay_current_portrait"
  | "stay_primary_landscape"
  | "stay_primary_portrait"
  | "stop"
  | "stop_screen_share"
  | "storage"
  | "store"
  | "store_mall_directory"
  | "straighten"
  | "streetview"
  | "strikethrough_s"
  | "style"
  | "subdirectory_arrow_left"
  | "subdirectory_arrow_right"
  | "subject"
  | "subscriptions"
  | "subtitles"
  | "subway"
  | "supervisor_account"
  | "surround_sound"
  | "swap_calls"
  | "swap_horiz"
  | "swap_vert"
  | "swap_vertical_circle"
  | "switch_camera"
  | "switch_video"
  | "sync"
  | "sync_disabled"
  | "sync_problem"
  | "system_update"
  | "system_update_alt"
  | "tab"
  | "tab_unselected"
  | "tablet"
  | "tablet_android"
  | "tablet_mac"
  | "tag_faces"
  | "tap_and_play"
  | "terrain"
  | "text_fields"
  | "text_format"
  | "textsms"
  | "texture"
  | "theaters"
  | "thumb_down"
  | "thumb_up"
  | "thumbs_up_down"
  | "time_to_leave"
  | "timelapse"
  | "timeline"
  | "timer"
  | "timer_10"
  | "timer_3"
  | "timer_off"
  | "title"
  | "toc"
  | "today"
  | "toll"
  | "tonality"
  | "touch_app"
  | "toys"
  | "track_changes"
  | "traffic"
  | "train"
  | "tram"
  | "transfer_within_a_station"
  | "transform"
  | "translate"
  | "trending_down"
  | "trending_flat"
  | "trending_up"
  | "tune"
  | "turned_in"
  | "turned_in_not"
  | "tv"
  | "unarchive"
  | "undo"
  | "unfold_less"
  | "unfold_more"
  | "update"
  | "usb"
  | "verified_user"
  | "vertical_align_bottom"
  | "vertical_align_center"
  | "vertical_align_top"
  | "vibration"
  | "video_call"
  | "video_label"
  | "video_library"
  | "videocam"
  | "videocam_off"
  | "videogame_asset"
  | "view_agenda"
  | "view_array"
  | "view_carousel"
  | "view_column"
  | "view_comfy"
  | "view_compact"
  | "view_day"
  | "view_headline"
  | "view_list"
  | "view_module"
  | "view_quilt"
  | "view_stream"
  | "view_week"
  | "vignette"
  | "visibility"
  | "visibility_off"
  | "voice_chat"
  | "voicemail"
  | "volume_down"
  | "volume_mute"
  | "volume_off"
  | "volume_up"
  | "vpn_key"
  | "vpn_lock"
  | "wallpaper"
  | "warning"
  | "watch"
  | "watch_later"
  | "wb_auto"
  | "wb_cloudy"
  | "wb_incandescent"
  | "wb_iridescent"
  | "wb_sunny"
  | "wc"
  | "web"
  | "web_asset"
  | "weekend"
  | "whatshot"
  | "widgets"
  | "wifi"
  | "wifi_lock"
  | "wifi_tethering"
  | "work"
  | "wrap_text"
  | "youtube_searched_for"
  | "zoom_in"
  | "zoom_out"
  | "zoom_out_map";

let fontMap = {
  "3d_rotation": "&#xe84d;",
  ac_unit: "&#xeb3b;",
  access_alarm: "&#xe190;",
  access_alarms: "&#xe191;",
  access_time: "&#xe192;",
  accessibility: "&#xe84e;",
  accessible: "&#xe914;",
  account_balance: "&#xe84f;",
  account_balance_wallet: "&#xe850;",
  account_box: "&#xe851;",
  account_circle: "&#xe853;",
  adb: "&#xe60e;",
  add: "&#xe145;",
  add_a_photo: "&#xe439;",
  add_alarm: "&#xe193;",
  add_alert: "&#xe003;",
  add_box: "&#xe146;",
  add_circle: "&#xe147;",
  add_circle_outline: "&#xe148;",
  add_location: "&#xe567;",
  add_shopping_cart: "&#xe854;",
  add_to_photos: "&#xe39d;",
  add_to_queue: "&#xe05c;",
  adjust: "&#xe39e;",
  airline_seat_flat: "&#xe630;",
  airline_seat_flat_angled: "&#xe631;",
  airline_seat_individual_suite: "&#xe632;",
  airline_seat_legroom_extra: "&#xe633;",
  airline_seat_legroom_normal: "&#xe634;",
  airline_seat_legroom_reduced: "&#xe635;",
  airline_seat_recline_extra: "&#xe636;",
  airline_seat_recline_normal: "&#xe637;",
  airplanemode_active: "&#xe195;",
  airplanemode_inactive: "&#xe194;",
  airplay: "&#xe055;",
  airport_shuttle: "&#xeb3c;",
  alarm: "&#xe855;",
  alarm_add: "&#xe856;",
  alarm_off: "&#xe857;",
  alarm_on: "&#xe858;",
  album: "&#xe019;",
  all_inclusive: "&#xeb3d;",
  all_out: "&#xe90b;",
  android: "&#xe859;",
  announcement: "&#xe85a;",
  apps: "&#xe5c3;",
  archive: "&#xe149;",
  arrow_back: "&#xe5c4;",
  arrow_downward: "&#xe5db;",
  arrow_drop_down: "&#xe5c5;",
  arrow_drop_down_circle: "&#xe5c6;",
  arrow_drop_up: "&#xe5c7;",
  arrow_forward: "&#xe5c8;",
  arrow_upward: "&#xe5d8;",
  art_track: "&#xe060;",
  aspect_ratio: "&#xe85b;",
  assessment: "&#xe85c;",
  assignment: "&#xe85d;",
  assignment_ind: "&#xe85e;",
  assignment_late: "&#xe85f;",
  assignment_return: "&#xe860;",
  assignment_returned: "&#xe861;",
  assignment_turned_in: "&#xe862;",
  assistant: "&#xe39f;",
  assistant_photo: "&#xe3a0;",
  attach_file: "&#xe226;",
  attach_money: "&#xe227;",
  attachment: "&#xe2bc;",
  audiotrack: "&#xe3a1;",
  autorenew: "&#xe863;",
  av_timer: "&#xe01b;",
  backspace: "&#xe14a;",
  backup: "&#xe864;",
  battery_alert: "&#xe19c;",
  battery_charging_full: "&#xe1a3;",
  battery_full: "&#xe1a4;",
  battery_std: "&#xe1a5;",
  battery_unknown: "&#xe1a6;",
  beach_access: "&#xeb3e;",
  beenhere: "&#xe52d;",
  block: "&#xe14b;",
  bluetooth: "&#xe1a7;",
  bluetooth_audio: "&#xe60f;",
  bluetooth_connected: "&#xe1a8;",
  bluetooth_disabled: "&#xe1a9;",
  bluetooth_searching: "&#xe1aa;",
  blur_circular: "&#xe3a2;",
  blur_linear: "&#xe3a3;",
  blur_off: "&#xe3a4;",
  blur_on: "&#xe3a5;",
  book: "&#xe865;",
  bookmark: "&#xe866;",
  bookmark_border: "&#xe867;",
  border_all: "&#xe228;",
  border_bottom: "&#xe229;",
  border_clear: "&#xe22a;",
  border_color: "&#xe22b;",
  border_horizontal: "&#xe22c;",
  border_inner: "&#xe22d;",
  border_left: "&#xe22e;",
  border_outer: "&#xe22f;",
  border_right: "&#xe230;",
  border_style: "&#xe231;",
  border_top: "&#xe232;",
  border_vertical: "&#xe233;",
  branding_watermark: "&#xe06b;",
  brightness_1: "&#xe3a6;",
  brightness_2: "&#xe3a7;",
  brightness_3: "&#xe3a8;",
  brightness_4: "&#xe3a9;",
  brightness_5: "&#xe3aa;",
  brightness_6: "&#xe3ab;",
  brightness_7: "&#xe3ac;",
  brightness_auto: "&#xe1ab;",
  brightness_high: "&#xe1ac;",
  brightness_low: "&#xe1ad;",
  brightness_medium: "&#xe1ae;",
  broken_image: "&#xe3ad;",
  brush: "&#xe3ae;",
  bubble_chart: "&#xe6dd;",
  bug_report: "&#xe868;",
  build: "&#xe869;",
  burst_mode: "&#xe43c;",
  business: "&#xe0af;",
  business_center: "&#xeb3f;",
  cached: "&#xe86a;",
  cake: "&#xe7e9;",
  call: "&#xe0b0;",
  call_end: "&#xe0b1;",
  call_made: "&#xe0b2;",
  call_merge: "&#xe0b3;",
  call_missed: "&#xe0b4;",
  call_missed_outgoing: "&#xe0e4;",
  call_received: "&#xe0b5;",
  call_split: "&#xe0b6;",
  call_to_action: "&#xe06c;",
  camera: "&#xe3af;",
  camera_alt: "&#xe3b0;",
  camera_enhance: "&#xe8fc;",
  camera_front: "&#xe3b1;",
  camera_rear: "&#xe3b2;",
  camera_roll: "&#xe3b3;",
  cancel: "&#xe5c9;",
  card_giftcard: "&#xe8f6;",
  card_membership: "&#xe8f7;",
  card_travel: "&#xe8f8;",
  casino: "&#xeb40;",
  cast: "&#xe307;",
  cast_connected: "&#xe308;",
  center_focus_strong: "&#xe3b4;",
  center_focus_weak: "&#xe3b5;",
  change_history: "&#xe86b;",
  chat: "&#xe0b7;",
  chat_bubble: "&#xe0ca;",
  chat_bubble_outline: "&#xe0cb;",
  check: "&#xe5ca;",
  check_box: "&#xe834;",
  check_box_outline_blank: "&#xe835;",
  check_circle: "&#xe86c;",
  chevron_left: "&#xe5cb;",
  chevron_right: "&#xe5cc;",
  child_care: "&#xeb41;",
  child_friendly: "&#xeb42;",
  chrome_reader_mode: "&#xe86d;",
  class: "&#xe86e;",
  clear: "&#xe14c;",
  clear_all: "&#xe0b8;",
  close: "&#xe5cd;",
  closed_caption: "&#xe01c;",
  cloud: "&#xe2bd;",
  cloud_circle: "&#xe2be;",
  cloud_done: "&#xe2bf;",
  cloud_download: "&#xe2c0;",
  cloud_off: "&#xe2c1;",
  cloud_queue: "&#xe2c2;",
  cloud_upload: "&#xe2c3;",
  code: "&#xe86f;",
  collections: "&#xe3b6;",
  collections_bookmark: "&#xe431;",
  color_lens: "&#xe3b7;",
  colorize: "&#xe3b8;",
  comment: "&#xe0b9;",
  compare: "&#xe3b9;",
  compare_arrows: "&#xe915;",
  computer: "&#xe30a;",
  confirmation_number: "&#xe638;",
  contact_mail: "&#xe0d0;",
  contact_phone: "&#xe0cf;",
  contacts: "&#xe0ba;",
  content_copy: "&#xe14d;",
  content_cut: "&#xe14e;",
  content_paste: "&#xe14f;",
  control_point: "&#xe3ba;",
  control_point_duplicate: "&#xe3bb;",
  copyright: "&#xe90c;",
  create: "&#xe150;",
  create_new_folder: "&#xe2cc;",
  credit_card: "&#xe870;",
  crop: "&#xe3be;",
  crop_16_9: "&#xe3bc;",
  crop_3_2: "&#xe3bd;",
  crop_5_4: "&#xe3bf;",
  crop_7_5: "&#xe3c0;",
  crop_din: "&#xe3c1;",
  crop_free: "&#xe3c2;",
  crop_landscape: "&#xe3c3;",
  crop_original: "&#xe3c4;",
  crop_portrait: "&#xe3c5;",
  crop_rotate: "&#xe437;",
  crop_square: "&#xe3c6;",
  dashboard: "&#xe871;",
  data_usage: "&#xe1af;",
  date_range: "&#xe916;",
  dehaze: "&#xe3c7;",
  delete: "&#xe872;",
  delete_forever: "&#xe92b;",
  delete_sweep: "&#xe16c;",
  description: "&#xe873;",
  desktop_mac: "&#xe30b;",
  desktop_windows: "&#xe30c;",
  details: "&#xe3c8;",
  developer_board: "&#xe30d;",
  developer_mode: "&#xe1b0;",
  device_hub: "&#xe335;",
  devices: "&#xe1b1;",
  devices_other: "&#xe337;",
  dialer_sip: "&#xe0bb;",
  dialpad: "&#xe0bc;",
  directions: "&#xe52e;",
  directions_bike: "&#xe52f;",
  directions_boat: "&#xe532;",
  directions_bus: "&#xe530;",
  directions_car: "&#xe531;",
  directions_railway: "&#xe534;",
  directions_run: "&#xe566;",
  directions_subway: "&#xe533;",
  directions_transit: "&#xe535;",
  directions_walk: "&#xe536;",
  disc_full: "&#xe610;",
  dns: "&#xe875;",
  do_not_disturb: "&#xe612;",
  do_not_disturb_alt: "&#xe611;",
  do_not_disturb_off: "&#xe643;",
  do_not_disturb_on: "&#xe644;",
  dock: "&#xe30e;",
  domain: "&#xe7ee;",
  done: "&#xe876;",
  done_all: "&#xe877;",
  donut_large: "&#xe917;",
  donut_small: "&#xe918;",
  drafts: "&#xe151;",
  drag_handle: "&#xe25d;",
  drive_eta: "&#xe613;",
  dvr: "&#xe1b2;",
  edit: "&#xe3c9;",
  edit_location: "&#xe568;",
  eject: "&#xe8fb;",
  email: "&#xe0be;",
  enhanced_encryption: "&#xe63f;",
  equalizer: "&#xe01d;",
  error: "&#xe000;",
  error_outline: "&#xe001;",
  euro_symbol: "&#xe926;",
  ev_station: "&#xe56d;",
  event: "&#xe878;",
  event_available: "&#xe614;",
  event_busy: "&#xe615;",
  event_note: "&#xe616;",
  event_seat: "&#xe903;",
  exit_to_app: "&#xe879;",
  expand_less: "&#xe5ce;",
  expand_more: "&#xe5cf;",
  explicit: "&#xe01e;",
  explore: "&#xe87a;",
  exposure: "&#xe3ca;",
  exposure_neg_1: "&#xe3cb;",
  exposure_neg_2: "&#xe3cc;",
  exposure_plus_1: "&#xe3cd;",
  exposure_plus_2: "&#xe3ce;",
  exposure_zero: "&#xe3cf;",
  extension: "&#xe87b;",
  face: "&#xe87c;",
  fast_forward: "&#xe01f;",
  fast_rewind: "&#xe020;",
  favorite: "&#xe87d;",
  favorite_border: "&#xe87e;",
  featured_play_list: "&#xe06d;",
  featured_video: "&#xe06e;",
  feedback: "&#xe87f;",
  fiber_dvr: "&#xe05d;",
  fiber_manual_record: "&#xe061;",
  fiber_new: "&#xe05e;",
  fiber_pin: "&#xe06a;",
  fiber_smart_record: "&#xe062;",
  file_download: "&#xe2c4;",
  file_upload: "&#xe2c6;",
  filter: "&#xe3d3;",
  filter_1: "&#xe3d0;",
  filter_2: "&#xe3d1;",
  filter_3: "&#xe3d2;",
  filter_4: "&#xe3d4;",
  filter_5: "&#xe3d5;",
  filter_6: "&#xe3d6;",
  filter_7: "&#xe3d7;",
  filter_8: "&#xe3d8;",
  filter_9: "&#xe3d9;",
  filter_9_plus: "&#xe3da;",
  filter_b_and_w: "&#xe3db;",
  filter_center_focus: "&#xe3dc;",
  filter_drama: "&#xe3dd;",
  filter_frames: "&#xe3de;",
  filter_hdr: "&#xe3df;",
  filter_list: "&#xe152;",
  filter_none: "&#xe3e0;",
  filter_tilt_shift: "&#xe3e2;",
  filter_vintage: "&#xe3e3;",
  find_in_page: "&#xe880;",
  find_replace: "&#xe881;",
  fingerprint: "&#xe90d;",
  first_page: "&#xe5dc;",
  fitness_center: "&#xeb43;",
  flag: "&#xe153;",
  flare: "&#xe3e4;",
  flash_auto: "&#xe3e5;",
  flash_off: "&#xe3e6;",
  flash_on: "&#xe3e7;",
  flight: "&#xe539;",
  flight_land: "&#xe904;",
  flight_takeoff: "&#xe905;",
  flip: "&#xe3e8;",
  flip_to_back: "&#xe882;",
  flip_to_front: "&#xe883;",
  folder: "&#xe2c7;",
  folder_open: "&#xe2c8;",
  folder_shared: "&#xe2c9;",
  folder_special: "&#xe617;",
  font_download: "&#xe167;",
  format_align_center: "&#xe234;",
  format_align_justify: "&#xe235;",
  format_align_left: "&#xe236;",
  format_align_right: "&#xe237;",
  format_bold: "&#xe238;",
  format_clear: "&#xe239;",
  format_color_fill: "&#xe23a;",
  format_color_reset: "&#xe23b;",
  format_color_text: "&#xe23c;",
  format_indent_decrease: "&#xe23d;",
  format_indent_increase: "&#xe23e;",
  format_italic: "&#xe23f;",
  format_line_spacing: "&#xe240;",
  format_list_bulleted: "&#xe241;",
  format_list_numbered: "&#xe242;",
  format_paint: "&#xe243;",
  format_quote: "&#xe244;",
  format_shapes: "&#xe25e;",
  format_size: "&#xe245;",
  format_strikethrough: "&#xe246;",
  format_textdirection_l_to_r: "&#xe247;",
  format_textdirection_r_to_l: "&#xe248;",
  format_underlined: "&#xe249;",
  forum: "&#xe0bf;",
  forward: "&#xe154;",
  forward_10: "&#xe056;",
  forward_30: "&#xe057;",
  forward_5: "&#xe058;",
  free_breakfast: "&#xeb44;",
  fullscreen: "&#xe5d0;",
  fullscreen_exit: "&#xe5d1;",
  functions: "&#xe24a;",
  g_translate: "&#xe927;",
  gamepad: "&#xe30f;",
  games: "&#xe021;",
  gavel: "&#xe90e;",
  gesture: "&#xe155;",
  get_app: "&#xe884;",
  gif: "&#xe908;",
  golf_course: "&#xeb45;",
  gps_fixed: "&#xe1b3;",
  gps_not_fixed: "&#xe1b4;",
  gps_off: "&#xe1b5;",
  grade: "&#xe885;",
  gradient: "&#xe3e9;",
  grain: "&#xe3ea;",
  graphic_eq: "&#xe1b8;",
  grid_off: "&#xe3eb;",
  grid_on: "&#xe3ec;",
  group: "&#xe7ef;",
  group_add: "&#xe7f0;",
  group_work: "&#xe886;",
  hd: "&#xe052;",
  hdr_off: "&#xe3ed;",
  hdr_on: "&#xe3ee;",
  hdr_strong: "&#xe3f1;",
  hdr_weak: "&#xe3f2;",
  headset: "&#xe310;",
  headset_mic: "&#xe311;",
  healing: "&#xe3f3;",
  hearing: "&#xe023;",
  help: "&#xe887;",
  help_outline: "&#xe8fd;",
  high_quality: "&#xe024;",
  highlight: "&#xe25f;",
  highlight_off: "&#xe888;",
  history: "&#xe889;",
  home: "&#xe88a;",
  hot_tub: "&#xeb46;",
  hotel: "&#xe53a;",
  hourglass_empty: "&#xe88b;",
  hourglass_full: "&#xe88c;",
  http: "&#xe902;",
  https: "&#xe88d;",
  image: "&#xe3f4;",
  image_aspect_ratio: "&#xe3f5;",
  import_contacts: "&#xe0e0;",
  import_export: "&#xe0c3;",
  important_devices: "&#xe912;",
  inbox: "&#xe156;",
  indeterminate_check_box: "&#xe909;",
  info: "&#xe88e;",
  info_outline: "&#xe88f;",
  input: "&#xe890;",
  insert_chart: "&#xe24b;",
  insert_comment: "&#xe24c;",
  insert_drive_file: "&#xe24d;",
  insert_emoticon: "&#xe24e;",
  insert_invitation: "&#xe24f;",
  insert_link: "&#xe250;",
  insert_photo: "&#xe251;",
  invert_colors: "&#xe891;",
  invert_colors_off: "&#xe0c4;",
  iso: "&#xe3f6;",
  keyboard: "&#xe312;",
  keyboard_arrow_down: "&#xe313;",
  keyboard_arrow_left: "&#xe314;",
  keyboard_arrow_right: "&#xe315;",
  keyboard_arrow_up: "&#xe316;",
  keyboard_backspace: "&#xe317;",
  keyboard_capslock: "&#xe318;",
  keyboard_hide: "&#xe31a;",
  keyboard_return: "&#xe31b;",
  keyboard_tab: "&#xe31c;",
  keyboard_voice: "&#xe31d;",
  kitchen: "&#xeb47;",
  label: "&#xe892;",
  label_outline: "&#xe893;",
  landscape: "&#xe3f7;",
  language: "&#xe894;",
  laptop: "&#xe31e;",
  laptop_chromebook: "&#xe31f;",
  laptop_mac: "&#xe320;",
  laptop_windows: "&#xe321;",
  last_page: "&#xe5dd;",
  launch: "&#xe895;",
  layers: "&#xe53b;",
  layers_clear: "&#xe53c;",
  leak_add: "&#xe3f8;",
  leak_remove: "&#xe3f9;",
  lens: "&#xe3fa;",
  library_add: "&#xe02e;",
  library_books: "&#xe02f;",
  library_music: "&#xe030;",
  lightbulb_outline: "&#xe90f;",
  line_style: "&#xe919;",
  line_weight: "&#xe91a;",
  linear_scale: "&#xe260;",
  link: "&#xe157;",
  linked_camera: "&#xe438;",
  list: "&#xe896;",
  live_help: "&#xe0c6;",
  live_tv: "&#xe639;",
  local_activity: "&#xe53f;",
  local_airport: "&#xe53d;",
  local_atm: "&#xe53e;",
  local_bar: "&#xe540;",
  local_cafe: "&#xe541;",
  local_car_wash: "&#xe542;",
  local_convenience_store: "&#xe543;",
  local_dining: "&#xe556;",
  local_drink: "&#xe544;",
  local_florist: "&#xe545;",
  local_gas_station: "&#xe546;",
  local_grocery_store: "&#xe547;",
  local_hospital: "&#xe548;",
  local_hotel: "&#xe549;",
  local_laundry_service: "&#xe54a;",
  local_library: "&#xe54b;",
  local_mall: "&#xe54c;",
  local_movies: "&#xe54d;",
  local_offer: "&#xe54e;",
  local_parking: "&#xe54f;",
  local_pharmacy: "&#xe550;",
  local_phone: "&#xe551;",
  local_pizza: "&#xe552;",
  local_play: "&#xe553;",
  local_post_office: "&#xe554;",
  local_printshop: "&#xe555;",
  local_see: "&#xe557;",
  local_shipping: "&#xe558;",
  local_taxi: "&#xe559;",
  location_city: "&#xe7f1;",
  location_disabled: "&#xe1b6;",
  location_off: "&#xe0c7;",
  location_on: "&#xe0c8;",
  location_searching: "&#xe1b7;",
  lock: "&#xe897;",
  lock_open: "&#xe898;",
  lock_outline: "&#xe899;",
  looks: "&#xe3fc;",
  looks_3: "&#xe3fb;",
  looks_4: "&#xe3fd;",
  looks_5: "&#xe3fe;",
  looks_6: "&#xe3ff;",
  looks_one: "&#xe400;",
  looks_two: "&#xe401;",
  loop: "&#xe028;",
  loupe: "&#xe402;",
  low_priority: "&#xe16d;",
  loyalty: "&#xe89a;",
  mail: "&#xe158;",
  mail_outline: "&#xe0e1;",
  map: "&#xe55b;",
  markunread: "&#xe159;",
  markunread_mailbox: "&#xe89b;",
  memory: "&#xe322;",
  menu: "&#xe5d2;",
  merge_type: "&#xe252;",
  message: "&#xe0c9;",
  mic: "&#xe029;",
  mic_none: "&#xe02a;",
  mic_off: "&#xe02b;",
  mms: "&#xe618;",
  mode_comment: "&#xe253;",
  mode_edit: "&#xe254;",
  monetization_on: "&#xe263;",
  money_off: "&#xe25c;",
  monochrome_photos: "&#xe403;",
  mood: "&#xe7f2;",
  mood_bad: "&#xe7f3;",
  more: "&#xe619;",
  more_horiz: "&#xe5d3;",
  more_vert: "&#xe5d4;",
  motorcycle: "&#xe91b;",
  mouse: "&#xe323;",
  move_to_inbox: "&#xe168;",
  movie: "&#xe02c;",
  movie_creation: "&#xe404;",
  movie_filter: "&#xe43a;",
  multiline_chart: "&#xe6df;",
  music_note: "&#xe405;",
  music_video: "&#xe063;",
  my_location: "&#xe55c;",
  nature: "&#xe406;",
  nature_people: "&#xe407;",
  navigate_before: "&#xe408;",
  navigate_next: "&#xe409;",
  navigation: "&#xe55d;",
  near_me: "&#xe569;",
  network_cell: "&#xe1b9;",
  network_check: "&#xe640;",
  network_locked: "&#xe61a;",
  network_wifi: "&#xe1ba;",
  new_releases: "&#xe031;",
  next_week: "&#xe16a;",
  nfc: "&#xe1bb;",
  no_encryption: "&#xe641;",
  no_sim: "&#xe0cc;",
  not_interested: "&#xe033;",
  note: "&#xe06f;",
  note_add: "&#xe89c;",
  notifications: "&#xe7f4;",
  notifications_active: "&#xe7f7;",
  notifications_none: "&#xe7f5;",
  notifications_off: "&#xe7f6;",
  notifications_paused: "&#xe7f8;",
  offline_pin: "&#xe90a;",
  ondemand_video: "&#xe63a;",
  opacity: "&#xe91c;",
  open_in_browser: "&#xe89d;",
  open_in_new: "&#xe89e;",
  open_with: "&#xe89f;",
  pages: "&#xe7f9;",
  pageview: "&#xe8a0;",
  palette: "&#xe40a;",
  pan_tool: "&#xe925;",
  panorama: "&#xe40b;",
  panorama_fish_eye: "&#xe40c;",
  panorama_horizontal: "&#xe40d;",
  panorama_vertical: "&#xe40e;",
  panorama_wide_angle: "&#xe40f;",
  party_mode: "&#xe7fa;",
  pause: "&#xe034;",
  pause_circle_filled: "&#xe035;",
  pause_circle_outline: "&#xe036;",
  payment: "&#xe8a1;",
  people: "&#xe7fb;",
  people_outline: "&#xe7fc;",
  perm_camera_mic: "&#xe8a2;",
  perm_contact_calendar: "&#xe8a3;",
  perm_data_setting: "&#xe8a4;",
  perm_device_information: "&#xe8a5;",
  perm_identity: "&#xe8a6;",
  perm_media: "&#xe8a7;",
  perm_phone_msg: "&#xe8a8;",
  perm_scan_wifi: "&#xe8a9;",
  person: "&#xe7fd;",
  person_add: "&#xe7fe;",
  person_outline: "&#xe7ff;",
  person_pin: "&#xe55a;",
  person_pin_circle: "&#xe56a;",
  personal_video: "&#xe63b;",
  pets: "&#xe91d;",
  phone: "&#xe0cd;",
  phone_android: "&#xe324;",
  phone_bluetooth_speaker: "&#xe61b;",
  phone_forwarded: "&#xe61c;",
  phone_in_talk: "&#xe61d;",
  phone_iphone: "&#xe325;",
  phone_locked: "&#xe61e;",
  phone_missed: "&#xe61f;",
  phone_paused: "&#xe620;",
  phonelink: "&#xe326;",
  phonelink_erase: "&#xe0db;",
  phonelink_lock: "&#xe0dc;",
  phonelink_off: "&#xe327;",
  phonelink_ring: "&#xe0dd;",
  phonelink_setup: "&#xe0de;",
  photo: "&#xe410;",
  photo_album: "&#xe411;",
  photo_camera: "&#xe412;",
  photo_filter: "&#xe43b;",
  photo_library: "&#xe413;",
  photo_size_select_actual: "&#xe432;",
  photo_size_select_large: "&#xe433;",
  photo_size_select_small: "&#xe434;",
  picture_as_pdf: "&#xe415;",
  picture_in_picture: "&#xe8aa;",
  picture_in_picture_alt: "&#xe911;",
  pie_chart: "&#xe6c4;",
  pie_chart_outlined: "&#xe6c5;",
  pin_drop: "&#xe55e;",
  place: "&#xe55f;",
  play_arrow: "&#xe037;",
  play_circle_filled: "&#xe038;",
  play_circle_outline: "&#xe039;",
  play_for_work: "&#xe906;",
  playlist_add: "&#xe03b;",
  playlist_add_check: "&#xe065;",
  playlist_play: "&#xe05f;",
  plus_one: "&#xe800;",
  poll: "&#xe801;",
  polymer: "&#xe8ab;",
  pool: "&#xeb48;",
  portable_wifi_off: "&#xe0ce;",
  portrait: "&#xe416;",
  power: "&#xe63c;",
  power_input: "&#xe336;",
  power_settings_new: "&#xe8ac;",
  pregnant_woman: "&#xe91e;",
  present_to_all: "&#xe0df;",
  print: "&#xe8ad;",
  priority_high: "&#xe645;",
  public: "&#xe80b;",
  publish: "&#xe255;",
  query_builder: "&#xe8ae;",
  question_answer: "&#xe8af;",
  queue: "&#xe03c;",
  queue_music: "&#xe03d;",
  queue_play_next: "&#xe066;",
  radio: "&#xe03e;",
  radio_button_checked: "&#xe837;",
  radio_button_unchecked: "&#xe836;",
  rate_review: "&#xe560;",
  receipt: "&#xe8b0;",
  recent_actors: "&#xe03f;",
  record_voice_over: "&#xe91f;",
  redeem: "&#xe8b1;",
  redo: "&#xe15a;",
  refresh: "&#xe5d5;",
  remove: "&#xe15b;",
  remove_circle: "&#xe15c;",
  remove_circle_outline: "&#xe15d;",
  remove_from_queue: "&#xe067;",
  remove_red_eye: "&#xe417;",
  remove_shopping_cart: "&#xe928;",
  reorder: "&#xe8fe;",
  repeat: "&#xe040;",
  repeat_one: "&#xe041;",
  replay: "&#xe042;",
  replay_10: "&#xe059;",
  replay_30: "&#xe05a;",
  replay_5: "&#xe05b;",
  reply: "&#xe15e;",
  reply_all: "&#xe15f;",
  report: "&#xe160;",
  report_problem: "&#xe8b2;",
  restaurant: "&#xe56c;",
  restaurant_menu: "&#xe561;",
  restore: "&#xe8b3;",
  restore_page: "&#xe929;",
  ring_volume: "&#xe0d1;",
  room: "&#xe8b4;",
  room_service: "&#xeb49;",
  rotate_90_degrees_ccw: "&#xe418;",
  rotate_left: "&#xe419;",
  rotate_right: "&#xe41a;",
  rounded_corner: "&#xe920;",
  router: "&#xe328;",
  rowing: "&#xe921;",
  rss_feed: "&#xe0e5;",
  rv_hookup: "&#xe642;",
  satellite: "&#xe562;",
  save: "&#xe161;",
  scanner: "&#xe329;",
  schedule: "&#xe8b5;",
  school: "&#xe80c;",
  screen_lock_landscape: "&#xe1be;",
  screen_lock_portrait: "&#xe1bf;",
  screen_lock_rotation: "&#xe1c0;",
  screen_rotation: "&#xe1c1;",
  screen_share: "&#xe0e2;",
  sd_card: "&#xe623;",
  sd_storage: "&#xe1c2;",
  search: "&#xe8b6;",
  security: "&#xe32a;",
  select_all: "&#xe162;",
  send: "&#xe163;",
  sentiment_dissatisfied: "&#xe811;",
  sentiment_neutral: "&#xe812;",
  sentiment_satisfied: "&#xe813;",
  sentiment_very_dissatisfied: "&#xe814;",
  sentiment_very_satisfied: "&#xe815;",
  settings: "&#xe8b8;",
  settings_applications: "&#xe8b9;",
  settings_backup_restore: "&#xe8ba;",
  settings_bluetooth: "&#xe8bb;",
  settings_brightness: "&#xe8bd;",
  settings_cell: "&#xe8bc;",
  settings_ethernet: "&#xe8be;",
  settings_input_antenna: "&#xe8bf;",
  settings_input_component: "&#xe8c0;",
  settings_input_composite: "&#xe8c1;",
  settings_input_hdmi: "&#xe8c2;",
  settings_input_svideo: "&#xe8c3;",
  settings_overscan: "&#xe8c4;",
  settings_phone: "&#xe8c5;",
  settings_power: "&#xe8c6;",
  settings_remote: "&#xe8c7;",
  settings_system_daydream: "&#xe1c3;",
  settings_voice: "&#xe8c8;",
  share: "&#xe80d;",
  shop: "&#xe8c9;",
  shop_two: "&#xe8ca;",
  shopping_basket: "&#xe8cb;",
  shopping_cart: "&#xe8cc;",
  short_text: "&#xe261;",
  show_chart: "&#xe6e1;",
  shuffle: "&#xe043;",
  signal_cellular_4_bar: "&#xe1c8;",
  signal_cellular_connected_no_internet_4_bar: "&#xe1cd;",
  signal_cellular_no_sim: "&#xe1ce;",
  signal_cellular_null: "&#xe1cf;",
  signal_cellular_off: "&#xe1d0;",
  signal_wifi_4_bar: "&#xe1d8;",
  signal_wifi_4_bar_lock: "&#xe1d9;",
  signal_wifi_off: "&#xe1da;",
  sim_card: "&#xe32b;",
  sim_card_alert: "&#xe624;",
  skip_next: "&#xe044;",
  skip_previous: "&#xe045;",
  slideshow: "&#xe41b;",
  slow_motion_video: "&#xe068;",
  smartphone: "&#xe32c;",
  smoke_free: "&#xeb4a;",
  smoking_rooms: "&#xeb4b;",
  sms: "&#xe625;",
  sms_failed: "&#xe626;",
  snooze: "&#xe046;",
  sort: "&#xe164;",
  sort_by_alpha: "&#xe053;",
  spa: "&#xeb4c;",
  space_bar: "&#xe256;",
  speaker: "&#xe32d;",
  speaker_group: "&#xe32e;",
  speaker_notes: "&#xe8cd;",
  speaker_notes_off: "&#xe92a;",
  speaker_phone: "&#xe0d2;",
  spellcheck: "&#xe8ce;",
  star: "&#xe838;",
  star_border: "&#xe83a;",
  star_half: "&#xe839;",
  stars: "&#xe8d0;",
  stay_current_landscape: "&#xe0d3;",
  stay_current_portrait: "&#xe0d4;",
  stay_primary_landscape: "&#xe0d5;",
  stay_primary_portrait: "&#xe0d6;",
  stop: "&#xe047;",
  stop_screen_share: "&#xe0e3;",
  storage: "&#xe1db;",
  store: "&#xe8d1;",
  store_mall_directory: "&#xe563;",
  straighten: "&#xe41c;",
  streetview: "&#xe56e;",
  strikethrough_s: "&#xe257;",
  style: "&#xe41d;",
  subdirectory_arrow_left: "&#xe5d9;",
  subdirectory_arrow_right: "&#xe5da;",
  subject: "&#xe8d2;",
  subscriptions: "&#xe064;",
  subtitles: "&#xe048;",
  subway: "&#xe56f;",
  supervisor_account: "&#xe8d3;",
  surround_sound: "&#xe049;",
  swap_calls: "&#xe0d7;",
  swap_horiz: "&#xe8d4;",
  swap_vert: "&#xe8d5;",
  swap_vertical_circle: "&#xe8d6;",
  switch_camera: "&#xe41e;",
  switch_video: "&#xe41f;",
  sync: "&#xe627;",
  sync_disabled: "&#xe628;",
  sync_problem: "&#xe629;",
  system_update: "&#xe62a;",
  system_update_alt: "&#xe8d7;",
  tab: "&#xe8d8;",
  tab_unselected: "&#xe8d9;",
  tablet: "&#xe32f;",
  tablet_android: "&#xe330;",
  tablet_mac: "&#xe331;",
  tag_faces: "&#xe420;",
  tap_and_play: "&#xe62b;",
  terrain: "&#xe564;",
  text_fields: "&#xe262;",
  text_format: "&#xe165;",
  textsms: "&#xe0d8;",
  texture: "&#xe421;",
  theaters: "&#xe8da;",
  thumb_down: "&#xe8db;",
  thumb_up: "&#xe8dc;",
  thumbs_up_down: "&#xe8dd;",
  time_to_leave: "&#xe62c;",
  timelapse: "&#xe422;",
  timeline: "&#xe922;",
  timer: "&#xe425;",
  timer_10: "&#xe423;",
  timer_3: "&#xe424;",
  timer_off: "&#xe426;",
  title: "&#xe264;",
  toc: "&#xe8de;",
  today: "&#xe8df;",
  toll: "&#xe8e0;",
  tonality: "&#xe427;",
  touch_app: "&#xe913;",
  toys: "&#xe332;",
  track_changes: "&#xe8e1;",
  traffic: "&#xe565;",
  train: "&#xe570;",
  tram: "&#xe571;",
  transfer_within_a_station: "&#xe572;",
  transform: "&#xe428;",
  translate: "&#xe8e2;",
  trending_down: "&#xe8e3;",
  trending_flat: "&#xe8e4;",
  trending_up: "&#xe8e5;",
  tune: "&#xe429;",
  turned_in: "&#xe8e6;",
  turned_in_not: "&#xe8e7;",
  tv: "&#xe333;",
  unarchive: "&#xe169;",
  undo: "&#xe166;",
  unfold_less: "&#xe5d6;",
  unfold_more: "&#xe5d7;",
  update: "&#xe923;",
  usb: "&#xe1e0;",
  verified_user: "&#xe8e8;",
  vertical_align_bottom: "&#xe258;",
  vertical_align_center: "&#xe259;",
  vertical_align_top: "&#xe25a;",
  vibration: "&#xe62d;",
  video_call: "&#xe070;",
  video_label: "&#xe071;",
  video_library: "&#xe04a;",
  videocam: "&#xe04b;",
  videocam_off: "&#xe04c;",
  videogame_asset: "&#xe338;",
  view_agenda: "&#xe8e9;",
  view_array: "&#xe8ea;",
  view_carousel: "&#xe8eb;",
  view_column: "&#xe8ec;",
  view_comfy: "&#xe42a;",
  view_compact: "&#xe42b;",
  view_day: "&#xe8ed;",
  view_headline: "&#xe8ee;",
  view_list: "&#xe8ef;",
  view_module: "&#xe8f0;",
  view_quilt: "&#xe8f1;",
  view_stream: "&#xe8f2;",
  view_week: "&#xe8f3;",
  vignette: "&#xe435;",
  visibility: "&#xe8f4;",
  visibility_off: "&#xe8f5;",
  voice_chat: "&#xe62e;",
  voicemail: "&#xe0d9;",
  volume_down: "&#xe04d;",
  volume_mute: "&#xe04e;",
  volume_off: "&#xe04f;",
  volume_up: "&#xe050;",
  vpn_key: "&#xe0da;",
  vpn_lock: "&#xe62f;",
  wallpaper: "&#xe1bc;",
  warning: "&#xe002;",
  watch: "&#xe334;",
  watch_later: "&#xe924;",
  wb_auto: "&#xe42c;",
  wb_cloudy: "&#xe42d;",
  wb_incandescent: "&#xe42e;",
  wb_iridescent: "&#xe436;",
  wb_sunny: "&#xe430;",
  wc: "&#xe63d;",
  web: "&#xe051;",
  web_asset: "&#xe069;",
  weekend: "&#xe16b;",
  whatshot: "&#xe80e;",
  widgets: "&#xe1bd;",
  wifi: "&#xe63e;",
  wifi_lock: "&#xe1e1;",
  wifi_tethering: "&#xe1e2;",
  work: "&#xe8f9;",
  wrap_text: "&#xe25b;",
  youtube_searched_for: "&#xe8fa;",
  zoom_in: "&#xe8ff;",
  zoom_out: "&#xe900;",
  zoom_out_map: "&#xe56b;",
} as const;

export type { IconName };

export { fontMap };
